/* ============================================================
   CONTENT
   Shorthand written the way a husband texts, not the way an app writes.
   {N} is swapped for her name if you set one.
   ============================================================ */

const MOODS = [
  {k:'morn', n:'Good morning'},
  {k:'miss', n:'Missing u'},
  {k:'thx',  n:'Thank u'},
  {k:'sorry',n:'Sorry'},
  {k:'time', n:'Making time'},
  {k:'faith',n:'Faith'},
  {k:'play', n:'Playful'},
  {k:'mum',  n:'As a mother'},
  {k:'night',n:'Goodnight'}
];

const MSG = {
morn:{sh:[
"gud morning {N}. i prayed 4 u b4 i got up.",
"morning. u were the first thing on my mind 2day.",
"gud morning my luv. dont skip breakfast, i know u.",
"morning {N}. buea cold today. sleep small more, i go sort the kids.",
"gud morning. wetin u wan make i buy on my way back?",
"morning beautiful. God keep u 2day.",
"i lov u. thats all. hav a soft day.",
"gud morning. no long tin, i just wanted u to know say i dey think of u.",
"morning {N}. leave the dishes, i go do dem when i reach.",
"woke up thanking God for u. gud morning.",
"gud morning. rest ur mind small 2day, u carry too much.",
"morning my wife. text me when u reach, make i know say u dey fine."
],pd:[
"gud morning {N}. i don pray for u before i comot bed.",
"morning oo. na u full my head since i wake.",
"gud morning my wife. no forget chop, u sabi say u dey forget.",
"morning. buea cold today no be small. cover ursef well.",
"gud morning. talk wetin i go buy for road.",
"morning {N}. God go keep u today, no fear.",
"i lov u. na all. make ur day soft.",
"gud morning. i just wan make u know say i dey think of u.",
"morning. leave the plate dem, i go wash when i land.",
"i wake dey thank God for u. gud morning oo.",
"gud morning {N}. no carry too much for head today.",
"morning my wife. when u reach, ping me make i know."
]},
miss:{sh:[
"thinking of u right now. no reason. just u.",
"i miss u n we dey the same house. na wa.",
"ur laugh dey my head since morning.",
"no gist. i just wan hear ur voice small.",
"counting hrs till i see u.",
"wish i was there right now {N}.",
"i dey here but my mind dey house.",
"missing u. no need 2 reply, i just wan say am.",
"i keep looking at ur pic. still my wife. still fine.",
"the house dey too quiet when u no dey. i notice.",
"5 more hrs n im home. dont eat without me.",
"i dey miss u pass wetin i sabi talk."
],pd:[
"i dey think of u now now. no reason. na just u.",
"i dey miss u and na the same house we dey. wahala.",
"ur laugh no wan comot my head since morning.",
"no gist. i just wan hear ur voice small.",
"i dey count hour till i see u.",
"i wish say i dey there now {N}.",
"body dey here, mind don go house.",
"i dey miss u. no need reply, i just wan talk am.",
"i dey look ur picture. u still fine no be small.",
"when u no dey, house dey too quiet. i dey notice am.",
"5 hour remain make i land. no chop finish.",
"i dey miss u pass as i fit talk am."
]},
thx:{sh:[
"thank u 4 the food last night. i ate am finish.",
"i see everything u do 4 this house. i dont say it enough. thank u.",
"u carry this family n still smile. i see u {N}.",
"thx 4 being patient w/ me. i know i hav not been easy.",
"u are a gud mother. i shld say it more.",
"thank u 4 not giving up on me.",
"i dont say thank u well. so, thank u. 4 everything.",
"the house looked so gud when i reached. thank u.",
"u hav been holding this home alone. i know. thank u n im sorry.",
"thx 4 how u handled the kids yesterday. u are better at this than me.",
"i notice the small things u do. even when i dont talk.",
"God gave me a gud wife. i no take am 4 granted again."
],pd:[
"thank u for the food yesterday. i chop am finish.",
"i dey see everytin wey u dey do for this house. i no dey talk am. thank u.",
"u dey carry this family and u still dey smile. i dey see u {N}.",
"thank u say u dey patient with me. i sabi say i no easy.",
"u be gud mother. i suppose talk am pass so.",
"thank u say u never tire for me.",
"i no sabi talk thank u well. but, thank u. for everytin.",
"house fine well when i land. thank u.",
"na u don dey hold this home alone. i sabi. thank u, and sorry.",
"thank u for how u take handle pikin dem yesterday. u sabi am pass me.",
"i dey see the small small tin wey u dey do. even when i no talk.",
"God give me gud wife. i no go take am for granted again."
]},
sorry:{sh:[
"i was wrong. no excuse. im sorry.",
"i hav not given u my time n na my fault. forgive me.",
"sorry 4 how i talked 2 u. that was not luv.",
"i dont want 2 sleep w/ this thing between us. can we talk 2nite?",
"im sorry. no long story. i just want 2 fix it.",
"u told me n i didnt listen. i heard u now. sorry {N}.",
"no defence from me 2day. u were right. im sorry.",
"i hav been present in the house but absent from u. i see it. im sorry.",
"sorry. i go do better n u go see am, not just hear am.",
"i owe u more than sorry. but let me start there.",
"i shldnt hav said that. it was wrong. forgive me.",
"i know say sorry don tire u. watch me instead."
],pd:[
"i do bad. no excuse. sorry.",
"i no dey give u my time and na my fault. forgive me.",
"sorry for how i take talk to u. that one no be love.",
"i no wan sleep with this tin for our middle. we fit yarn tonight?",
"i dey sorry. no long story. i just wan repair am.",
"u talk am and i no listen. i don hear now. sorry {N}.",
"i no get defence today. na u right. sorry.",
"i dey for house but i no dey for u. i don see am. sorry.",
"sorry. i go do beta and u go see am, no be only hear am.",
"i owe u pass sorry. but make i start from there.",
"i no suppose talk that tin. e bad. forgive me.",
"i sabi say sorry don tire u. watch me instead."
]},
time:{sh:[
"friday evening is yours. no phone. just us. wetin u wan do?",
"come make we waka small this evening. just the 2 of us.",
"clear 2mrw evening 4 me. no kids, im taking u out.",
"im leaving work early 2day so we can sit n talk.",
"sunday after service, u n me. limbe. i don plan am.",
"phone off from 8pm 2nite. that time na ur own.",
"tell me one thing u miss doing w/ me. we do am this week.",
"i booked nothing fancy. just 2 chairs n u. is that ok?",
"lets waka go muea market together like b4. u remember?",
"every wednesday evening from now na our own. put am for ur head.",
"no work talk 2nite. just u n me.",
"give me 1 hr 2nite {N}. no phone, no tv. just talk 2 me."
],pd:[
"friday evening na ur own. no phone. na just we. wetin u wan do?",
"make we waka small this evening. just the two of us.",
"free tomorrow evening for me. no pikin, i dey carry u comot.",
"i dey comot work early today make we sidon yarn.",
"sunday after service, na me and u. limbe. i don arrange am.",
"phone go off from 8pm tonight. that hour na ur own.",
"talk one tin wey u dey miss make we do together. we go do am this week.",
"i no book anytin big. na just two chair and u. e ok?",
"make we waka go muea market together like before. u remember?",
"every wednesday evening from now na our own. put am for head.",
"no work talk tonight. na just me and u.",
"give me one hour tonight {N}. no phone, no tv. just yarn with me."
]},
faith:{sh:[
"i prayed 4 u 2day. by name. God is not deaf.",
"family altar 8pm. u lead 2nite? i go handle the kids part.",
"reading psalm 34 2nite. lets read am together.",
"praying 4 ur peace 2day. isaiah 26:3.",
"God gave me u. i no take am 4 granted.",
"whatever dey worry u 2day, i don carry am go prayer.",
"lets pray together b4 we sleep, even 2 mins.",
"read prov 31 this morning n saw u for there. thats not flattery.",
"i asked God to make me the husband u shld hav had all along.",
"the kids need 2 see us pray together. lets start 2nite.",
"God dey hold this home even when i wasnt. lets rebuild am.",
"i put ur name b4 God this morning {N}."
],pd:[
"i don pray for u today. with ur name. God no deaf.",
"family altar 8pm. u go lead tonight? i go take the pikin dem part.",
"i dey read psalm 34 tonight. make we read am together.",
"i dey pray for ur peace today. isaiah 26:3.",
"na God give me u. i no go take am for granted.",
"wetin dey worry u today, i don carry am go prayer.",
"make we pray together before we sleep, even 2 minutes.",
"i read prov 31 this morning, na u i see there. no be sweet mouth.",
"i don beg God make e turn me the husband wey u for don get since.",
"pikin dem need see us pray together. make we start tonight.",
"na God dey hold this home even when i no dey. make we build am back.",
"i don put ur name before God this morning {N}."
]},
play:{sh:[
"u still fine pass every woman for buea. na fact.",
"rmbr that pink dress? i still see u like that.",
"if i had 2 choose again, na u. every time.",
"who told u say u can smile like that? na weapon.",
"i married up n everybody sabi.",
"ur cooking don spoil me. i cant eat outside again.",
"na u i dey come home for. no be the house.",
"i saw a woman resembling u 2day n i almost greeted her. na ur fault.",
"my wife dey fine. thats the whole message.",
"20 yrs from now i go still dey look u like this.",
"i dey brag abt u to pple. u no sabi.",
"come let me disturb u small."
],pd:[
"u still fine pass every woman for buea. na fact.",
"u remember that pink gown? na so i still dey see u.",
"if i go choose again, na u. every single time.",
"who tell u say u fit smile like that? na weapon be that.",
"i marry up and everybody sabi.",
"ur cooking don spoil me. i no fit chop outside again.",
"na u i dey come house for. no be the building.",
"i see one woman wey resemble u today, i nearly greet am. na ur fault.",
"my wife fine. na the whole message be that.",
"20 years from now i go still dey look u like this.",
"i dey blow ur trumpet give pple. u no even sabi.",
"come make i disturb u small."
]},
mum:{sh:[
"the kids are turning out well becos of u.",
"u are raising them right. dont doubt urself {N}.",
"i saw how u handled junior 2day. patient pass me.",
"they will remember ur voice praying. thats not small.",
"u are tired n u still show up 4 them. i see it.",
"our children are blessed. i tell them so.",
"u are a better parent than me n im learning from u.",
"dont be hard on urself abt them. u dey try well well.",
"i want us to train them together. no more leaving am 2 u alone.",
"whatever gud they become, na ur hand dey there."
],pd:[
"pikin dem dey turn out well because of u.",
"u dey raise dem well. no doubt ursef {N}.",
"i see how u take handle junior today. u patient pass me.",
"dem go remember ur voice as u dey pray. that one no be small tin.",
"u don tire and u still dey show up for dem. i dey see am.",
"our pikin dem blessed. i dey tell dem so.",
"u be beta parent pass me and i dey learn from u.",
"no dey hard ursef about dem. u dey try well well.",
"i wan make we train dem together. i no go leave am for u alone again.",
"whatever gud tin dem turn, na ur hand dey inside."
]},
night:{sh:[
"gudnight my luv. no worry abt 2mrw, we go handle am together.",
"b4 u sleep, thank u 4 2day.",
"reached late, sorry. sit down, let me warm the food.",
"sleep well {N}. i dey here.",
"gudnight. i lov u. no long tin.",
"lets not sleep vex. talk 2 me small.",
"i prayed 4 u n the kids. gudnight.",
"rest. u don do enough 2day.",
"gudnight. 2mrw i go do better than 2day.",
"i lov u. sleep. we dey fine."
],pd:[
"gudnight my luv. no worry about tomorrow, we go handle am together.",
"before u sleep, thank u for today.",
"i land late, sorry. sidon, make i warm the food.",
"sleep well {N}. i dey here.",
"gudnight. i lov u. no long tin.",
"make we no sleep with vex. yarn me small.",
"i don pray for u and the pikin dem. gudnight.",
"rest. u don do enough today.",
"gudnight. tomorrow i go do beta pass today.",
"i lov u. sleep. we go dey alright."
]}
};

/* ---- the five ways love shows up ---- */
const LOVES = [
  {mk:'W', nm:'Words that build her up',
   sub:'She needs to hear it, not assume it',
   v:'Pleasant words are as an honeycomb, sweet to the soul, and health to the bones.', vr:'Proverbs 16:24, KJV',
   p:'Some wives are starved not of provision but of praise. If the only words she hears from you are instructions, corrections and silence, she will conclude she is staff, not a wife. Solomon spent an entire book telling his wife what he saw when he looked at her. He was not exaggerating; he was feeding her.',
   d:['Say one specific thing a day. Not "you look nice" but "the way you handled Junior this evening was patient, more than I would have been."',
      'Praise her in front of the children. What they hear you say about their mother becomes what they believe about her, and about how a wife is treated.',
      'Never correct her in front of anyone. Not the children, not visitors, not your family. Correction is a closed-door matter.',
      'Kill the sarcasm entirely. Jokes at her expense are withdrawals, and Ephesians 4:29 gives you no room for them.',
      'When she tells you something hard, do not fix it in the first minute. Say "that sounds heavy" and let there be silence before advice.']},
  {mk:'T', nm:'Time she can count on',
   sub:'The one she says is missing',
   v:'Live joyfully with the wife whom thou lovest all the days of thy life.', vr:'Ecclesiastes 9:9, KJV',
   p:'You told me she says you are not giving her your time. Then this is the one. Quality time is a phrase busy men invented to feel better about giving less. Evans is blunt about it: nobody accepts quality over quantity in their profession, only at home. Time is the currency her heart actually accepts, and it cannot be substituted.',
   d:['Fix one evening a week that is hers, on the calendar, same day every week. Protect it like a meeting with your boss. Wednesday or Friday, and do not move it.',
      'Twenty unbroken minutes every night, phone face down in another room. Not television together, which is sitting near each other, not with each other.',
      'Walk with her. Around the quarter, to the market, to buy bread. Walking side by side makes talking easier than sitting face to face.',
      'Come home when you said you would. Being an hour late without a call teaches her that her evening is not worth a message.',
      'Give her time that costs you something. Time left over is not a gift; time taken from something you wanted is.']},
  {mk:'S', nm:'Service she did not have to ask for',
   sub:'Hands, not speeches',
   v:'If I then, your Lord and Master, have washed your feet; ye also ought to wash one another\u2019s feet.', vr:'John 13:14, KJV',
   p:'Christ knelt with a towel. Nothing in Scripture makes a husband too senior to carry a bucket. A wife who has been carrying the entire domestic load alone does not hear "I love you" as love; she hears it as a description of a feeling that has not yet cost you anything.',
   d:['Take one chore permanently and never hand it back. Not helping when asked, owning it. Dishes every night, or the children\u2019s baths, or the Saturday market run.',
      'Do the thing she has mentioned three times. You know what it is. The tap, the door, the wardrobe. Do it this week without being reminded again.',
      'Get up with the children in the night sometimes so she sleeps through.',
      'When she is cooking, be in the kitchen. Peel something. The company matters as much as the peeling.',
      'Never call it helping her. It is not her house that you assist with. It is your house.']},
  {mk:'G', nm:'Gifts that prove you thought of her',
   sub:'Small and frequent beats big and rare',
   v:'For God so loved the world, that he gave his only begotten Son.', vr:'John 3:16, KJV',
   p:'Love in Scripture gives. Abraham\u2019s servant brought out jewels for Rebekah before a word of the proposal was finished. But the size is not the signal. The signal is that you were somewhere without her and she was still on your mind, and you brought back proof.',
   d:['Bring something small home once a week. Groundnut, her fruit, puff-puff, a sachet of the thing she likes. Under five hundred francs is fine.',
      'Notice what she looks at and does not buy. That is the gift list, and she will never say it out loud.',
      'Write it by hand sometimes. A note left where she will find it alone is worth more than a message she reads in a crowd.',
      'Mark her days. Birthday, your wedding date, the day you first met. Put them in your phone tonight, with an alarm a week before.',
      'Do not use a gift to end an argument. That turns a gift into a payment, and she will feel the difference.']},
  {mk:'A', nm:'Affection that asks nothing back',
   sub:'Warmth, held honourably',
   v:'Let the husband render unto the wife due benevolence.', vr:'1 Corinthians 7:3, KJV',
   p:'Scripture is clear that a husband owes his wife tenderness, and it is equally clear that it is kept within marriage and kept pure. What most wives describe as missing is not the bedroom. It is the ordinary warmth outside it: a hand held, a hug in the kitchen, a touch on the shoulder as you pass. Affection that always leads somewhere stops feeling like affection and starts feeling like a request.',
   d:['Hug her for six seconds, not one. Count it. The short hug is a greeting; the long one is a statement.',
      'Touch her without it being an opening move. Hand on her back as you pass, hand held on the way to church.',
      'Greet her properly when you come in. Put the bag down, look at her, greet her before you greet your phone.',
      'Sit close to her when you sit. Same settee, not opposite chairs.',
      'Keep it honourable in public. In your setting, restraint in front of others is itself a form of respect for her, and the warmth belongs at home.']}
];

const SEVEN = [
  ['Day 1','Ask and only listen','Ask her what the last months have felt like. Do not defend yourself once. Not one sentence beginning with "but". Write down what she says afterwards.'],
  ['Day 2','Apologise with no conditions','Name one specific thing, not a general "sorry for everything". No explanation attached. "I have not given you my time. That was my choice and it was wrong."'],
  ['Day 3','Give twenty minutes','Phone in another room. Twenty minutes, nothing else happening. Ask about her day and ask a second question about the answer.'],
  ['Day 4','Take a chore permanently','Pick one and announce that it is yours now, for good. Then actually do it on day 5, 6 and 7 without being reminded.'],
  ['Day 5','Restart the altar','Fifteen minutes at the table with the children. A passage, one question, one prayer. Short. Let her see you lead it.'],
  ['Day 6','Take her out','Anywhere. A walk counts. The point is that you planned it and the children are not there.'],
  ['Day 7','Ask what changed','"Did this week feel different to you?" Then listen to the answer, including if the answer is not yet. Then do the next week.']
];

const TABLETIME = [
  ['1','Eat first, no phones','Nobody reaches for a device at the table. This alone changes a house within a week.'],
  ['2','Go round the table','Each person, including the smallest, says one good thing and one hard thing from their day. Parents go too, and answer honestly.'],
  ['3','Read short','Six to ten verses. If the children lose the thread, it was too long. Better a small portion they follow than a chapter they endure.'],
  ['4','Ask one question','Not a quiz they can fail. Ask what they noticed, or what they would have done. There are no wrong answers to that.'],
  ['5','Pray by name','Each child prays for one person out loud. Short prayers count. They are learning that God is spoken to, not only spoken about.'],
  ['6','End with a laugh','Evans insisted table time be enjoyable. A joke, a story, an impression. Children who enjoy the altar will keep it when they leave home.']
];

const TONY = [
  ['Kingdom parenting is purposeful, not perfect','Evans defines it as intentionally overseeing the transfer of the faith to the next generation so that children learn to live all of life under God\u2019s authority. Intentional is the operative word. Nothing here happens by drifting.'],
  ['The onus is on the parents','Paul writes to fathers and parents, not to governments, villages or schools. If the training does not happen at your table, it does not happen. No institution is coming to do this for you.'],
  ['Love is as love does','His whole treatment of 1 Corinthians 13 lands here. Children and wives conclude they are loved from what is done, not what is announced. Words unbacked by action eventually sound like noise to the people who live with you.'],
  ['Three pillars: encouragement, discipline, instruction','Encouragement is tied to who a child is, not what they achieved, which is what separates it from praise. Discipline forms self-control, not just compliance. Instruction is the content. Weak on any of the three and the home wobbles.'],
  ['Train them in the way <em>they</em> should go','Proverbs 22:6 is about a child\u2019s bent, their God-given wiring, not a guarantee that religious training locks in. Evans admits he pushed football at a son who was made to sing, and calls it loving himself rather than loving his son.'],
  ['Communication is not transmission','A message sent is not a message received. Real communication requires quantity time, eye contact, honest admission of your own mistakes, and settling anger before the day ends, as Ephesians 4:26 says.'],
  ['Return to the table','The family meal is where identity, correction, doctrine and laughter all happen at once. Evans calls the household that abandoned the table an endangered species. We traded the table for the tablet.'],
  ['Instil the virtues one at a time','Wisdom, integrity, faith, resiliency, purity, service. These are taught over years in ordinary moments, not delivered in one sitting.']
];

const TENETS = ['The Holy Bible','The Godhead','Virgin birth of Christ','Total depravity','Repentance','Restitution','Justification','Water baptism','The Lord\u2019s Supper','Sanctification','Holy Ghost baptism','Divine healing','Personal evangelism','Marriage','The Rapture','Resurrection of the dead','The Great Tribulation','Second coming of Christ','Christ\u2019s millennial reign','Great White Throne judgment','New heaven and new earth','Hell fire'];

const RHYTHM = [
  ['Sunday','Sunday school, then the worship service. Children have their own class, which is where much of the Sincere Milk material is reinforced.'],
  ['Monday','Bible study, worked through the Search the Scriptures manual across the whole church at the same time.'],
  ['Thursday','Revival service, with an emphasis on personal holiness and testimony.'],
  ['Daily','Family altar at home, plus personal reading. Bible studies for husband and wife, Sincere Milk for the children.'],
  ['Weekly','House caring fellowship in the neighbourhood, and outreach or visitation.']
];

/* ============================================================
   READING TRACKS  [reference, title, question for the children, prayer point]
   Short portions on purpose. A child who follows six verses is better
   fed than a child who endures a chapter.
   ============================================================ */

const CANON = [
["Genesis 1:1-13","God begins","What did God make before He made light?","That our home would begin each day with God, not with our worries"],
["Genesis 1:24-31","Made in His image","What makes people different from animals?","That each of our children would know they were made on purpose"],
["Genesis 2:15-25","The first marriage","Why did God say it was not good for the man to be alone?","For our own marriage, that we would be one and not two"],
["Genesis 3:1-13","Everything breaks","What was the very first question the serpent asked?","That we would not argue with what God has plainly said"],
["Genesis 4:1-12","Two brothers","Why was Cain angry?","Against jealousy taking root between our children"],
["Genesis 6:9-22","Noah builds","How long did Noah work with nobody agreeing with him?","For courage to obey when nobody around us is doing the same"],
["Genesis 8:15-22","Dry ground again","What was the first thing Noah did when he came out?","That thanksgiving would be our first reaction, not our last"],
["Genesis 12:1-9","Leave and go","What did God not tell Abram before he set out?","For faith to move before we can see the whole road"],
["Genesis 22:1-14","The mountain","What did Abraham say God would provide?","That we would hold nothing back from God"],
["Genesis 28:10-22","A ladder in the dark","Where was Jacob sleeping when God met him?","That God would meet us in the hardest season, not only the good one"],
["Genesis 37:12-28","Sold by his own","How do you think Joseph felt in that pit?","For our children when people they trust let them down"],
["Genesis 41:38-45","From prison to palace","How many years passed between the pit and the palace?","For patience while God is still working underground"],
["Genesis 45:1-15","Forgiving the unforgivable","What did Joseph say God had turned it into?","For grace to forgive inside this family quickly"],
["Exodus 2:1-10","A basket on the river","Who was brave in this story?","For mothers who protect their children at cost"],
["Exodus 3:1-15","The bush that burned","What excuse did Moses give?","That we would stop disqualifying ourselves from God's work"],
["Exodus 12:21-30","The night of the lamb","What was on the doorposts?","Thanking God for the blood of Christ over this house"],
["Exodus 14:10-31","A road through water","What did Moses tell the people to do?","For the impossible thing our family is facing now"],
["Exodus 16:11-21","Bread every morning","Why could they not store it up?","For today's provision, and trust for tomorrow's"],
["Exodus 20:1-17","Ten words","Which commandment is hardest in our house?","That our home would love God's law, not resent it"],
["Exodus 32:1-14","The golden calf","Why were the people so quick to forget?","Against idols of money, phone and status in our home"],
["Numbers 13:25-33","Ten said no, two said yes","What did Caleb see that the others missed?","For eyes that measure problems against God, not against ourselves"],
["Deuteronomy 6:1-9","Teach them at home","When were parents told to talk about God's words?","For our family altar, that it would not break again"],
["Joshua 1:1-9","Be strong","How many times is Joshua told to be courageous?","For courage in the specific fear each of us is carrying"],
["Joshua 6:12-20","Walls fall down","What weapon brought the wall down?","That obedience would matter more to us than strategy"],
["Joshua 24:14-18","Choose today","What did Joshua decide for his household?","That this household would serve the Lord, decided by us, not inherited"],
["Judges 6:11-24","The weakest in his family","What did the angel call Gideon?","That God's name for us would be louder than our self-doubt"],
["Judges 7:1-8","Three hundred is enough","Why did God make the army smaller?","That God alone would get the credit for what happens here"],
["Ruth 1:6-18","Where you go, I go","What did Ruth give up?","For loyalty in our family when it costs something"],
["Ruth 2:1-12","Kindness in the field","How did Boaz treat a stranger?","That our home would be kind to people who cannot repay us"],
["1 Samuel 1:9-20","A mother who prayed","What did Hannah do with what she asked for?","That we would give our children back to God, not hold them for ourselves"],
["1 Samuel 3:1-10","Speak, Lord","How many times did God call before Samuel understood?","That our children would learn to recognise God's voice young"],
["1 Samuel 16:1-13","God looks inside","What does God look at that people cannot see?","That we would raise hearts, not reputations"],
["1 Samuel 17:32-50","The giant","What did David bring instead of armour?","For our children facing something far bigger than them"],
["2 Samuel 9:1-11","Kindness to a forgotten man","Why did David look for Mephibosheth?","For someone in our extended family everyone has forgotten"],
["2 Samuel 12:1-13","Caught","What did David say when he was found out?","That we would confess quickly instead of covering up"],
["1 Kings 3:5-14","Ask for anything","What did Solomon not ask for?","For wisdom in the decisions our family faces this month"],
["1 Kings 18:20-39","Fire on the mountain","Why did Elijah pour water on the altar?","That God would be God in this house, with no rival"],
["1 Kings 19:1-13","A whisper after the fire","Where was God's voice?","For rest and quiet for whoever in this house is exhausted"],
["2 Kings 4:1-7","Oil that did not stop","What did the widow already have?","That God would multiply the little we have"],
["2 Kings 5:1-14","Wash seven times","Why was Naaman angry at first?","Against pride that refuses simple obedience"],
["2 Chronicles 20:1-17","The battle is not yours","What did Jehoshaphat do first?","For the fight our family cannot win by ourselves"],
["Nehemiah 1:1-11","A man who wept and then worked","What did Nehemiah do before he asked the king?","That prayer would come before planning in our home"],
["Nehemiah 4:1-14","Trowel in one hand","How did they build while under threat?","For strength to keep building while under pressure"],
["Esther 4:10-17","For such a time","What did Esther risk?","That our children would be brave in the place God puts them"],
["Job 1:13-22","Everything gone in a day","What did Job say after the news?","For a family we know who is grieving now"],
["Job 42:1-6,10","After the storm","What changed in Job by the end?","That suffering would deepen and not harden us"],
["Psalm 1","Two roads","What is the tree planted beside?","That our children would choose their friends carefully"],
["Psalm 23","The shepherd","What does the shepherd do in the dark valley?","For comfort in the valley one of us is walking through"],
["Psalm 34:1-10","Taste and see","What happened when the poor man cried?","That we would learn to praise before the answer comes"],
["Psalm 51:1-13","Make me clean","What did David ask God to create in him?","For a clean heart in each person at this table"],
["Psalm 91","Under His wings","What is promised to the one who dwells with God?","For protection over this house and everyone who travels from it"],
["Psalm 103","Bless the Lord","How far does God put our sins from us?","Thanking God for forgiveness we did not earn"],
["Psalm 119:1-16","Hidden in the heart","Why hide God's word in your heart?","For the memorising of Scripture in this family"],
["Psalm 127","Unless the Lord builds","Who builds the house?","That we would stop building this home in our own strength"],
["Psalm 139:1-18","Known completely","What did God know about you before you were born?","That each child would know they are fully known and fully loved"],
["Proverbs 1:1-9","Listen, my son","What does wisdom start with?","That our children would want wisdom, not just marks"],
["Proverbs 3:1-12","Trust and lean not","What must we not lean on?","For a decision where we do not understand what God is doing"],
["Proverbs 15:1-7","A soft answer","What turns away anger?","For the tone of voice used in this house"],
["Proverbs 22:1-9","Train up a child","What does it mean to train a child in his own way?","That we would study each child instead of comparing them"],
["Proverbs 31:10-31","A woman to be praised","What is praised about her at the end?","Thanking God for the mother of this home, out loud"],
["Ecclesiastes 3:1-14","A time for everything","What time is our family in right now?","For contentment in the season we are actually in"],
["Isaiah 6:1-8","Here am I","What did Isaiah say after he was cleansed?","That someone at this table would answer God's call"],
["Isaiah 40:25-31","They shall mount up","Who gets tired in this passage?","For renewed strength for the one who is worn out"],
["Isaiah 53","He carried it","Who was wounded, and for whom?","Thanking Christ for taking what belonged to us"],
["Jeremiah 29:10-14","Plans for you","What must we do to find Him?","For our children's future, that God's plan would win"],
["Daniel 1:1-17","Purpose in the heart","What did Daniel decide before the pressure came?","That our children would decide right things in advance"],
["Daniel 3:13-30","The furnace","What did the three say before they were thrown in?","For faith that holds even if God does not rescue us the way we want"],
["Daniel 6:10-23","The lions","What did Daniel keep doing even when it was illegal?","For consistency in prayer when it costs us"],
["Jonah 1:1-17","Running the other way","Where can you go from God?","For anyone in our family running from what God asked"],
["Jonah 3:1-10","A second chance","What did God do when Nineveh turned?","Thanking God for second chances in this family"],
["Malachi 2:13-16","God watches marriages","What does God say He hates?","For our marriage covenant, that we would guard it"],
["Matthew 1:18-25","The name Jesus","What does the name mean?","Worshipping Christ as the one who saves from sin"],
["Matthew 2:1-12","Wise men travel far","What did they do when they found Him?","That we would be willing to travel far to find Christ"],
["Matthew 5:1-16","Blessed are","Which of these is hardest?","That our family would be salt in Buea, not just in church"],
["Matthew 6:5-15","How to pray","What comes before asking for bread?","That prayer at this altar would be honest, not performed"],
["Matthew 6:25-34","Do not worry","What are we told to seek first?","Against the specific anxiety in this house this week"],
["Matthew 7:24-29","Two builders","What was the difference between the houses?","That we would do what we hear and not only hear it"],
["Matthew 14:22-33","Walking on water","What made Peter start sinking?","For eyes fixed on Christ instead of on the storm"],
["Matthew 18:21-35","Seventy times seven","Why was the servant wrong?","For forgiveness owed between two people in this family"],
["Mark 4:35-41","Peace, be still","What did Jesus ask them afterwards?","For calm in the middle of our present trouble"],
["Mark 10:13-16","Let the children come","What did Jesus do with the children?","That our children would be welcomed to Christ, not pushed to Him"],
["Luke 2:41-52","The boy in the temple","How did Jesus grow?","That our children would grow in wisdom, body, and favour with God and people"],
["Luke 10:25-37","Who is my neighbour?","Who actually helped?","For a neighbour on our street we have been ignoring"],
["Luke 15:11-24","The son who came home","What did the father do while the son was still far off?","For a family member who has wandered from God"],
["John 3:1-17","Born again","What did Jesus say must happen?","That every person at this table would be truly born again"],
["John 4:5-26","The woman at the well","What did Jesus offer her?","For someone we know who is thirsty and does not know why"],
["John 11:17-44","Lazarus, come out","What did Jesus do before the miracle?","For a situation in our family that looks dead"],
["John 13:1-17","The towel and the basin","What did the Lord do for His disciples?","That the head of this home would serve like Christ served"],
["John 19:16-30","It is finished","What were His last words?","Worshipping Christ for finishing what we could not"],
["John 20:1-18","The empty tomb","Who saw Him first?","Thanking God that the resurrection is a fact, not a feeling"],
["Acts 2:1-21","The Spirit comes","What happened to the frightened disciples?","For the filling of the Holy Ghost in this home"],
["Acts 16:16-34","Singing in prison","What were Paul and Silas doing at midnight?","For praise in our hardest hour"],
["Romans 8:28-39","Nothing can separate","What is the list of things that cannot separate us?","For assurance for anyone here who is doubting"],
["1 Corinthians 13","What love actually is","Which line describes us least?","That love in this house would be practised, not just preached"],
["Ephesians 5:22-33","Husbands and wives","What is marriage a picture of?","For our own marriage, measured honestly against this passage"],
["Ephesians 6:1-9","Children and parents","What is the first commandment with a promise?","For obedience and honour between us"],
["Philippians 4:4-13","Content in everything","What did Paul learn?","For contentment with what God has given this family"],
["Hebrews 11:1-16","Faith's roll call","What did they all die still holding?","That our faith would outlast our lifetime"],
["James 1:19-27","Doers, not hearers","What is the mirror in this passage?","That we would act on what we read this evening"],
["1 Peter 3:1-9","Living together with understanding","What is a husband warned about?","For understanding between husband and wife, and unhindered prayers"],
["Revelation 21:1-7","All things new","What will God wipe away?","That this family would arrive there together, with nobody missing"]
];

const CHARS = [
["Genesis 5:21-24","Enoch, the man who walked with God","What happened to Enoch in the end?","That our walk with God would be steady and daily"],
["Genesis 6:8-22","Noah, obedient when nobody agreed","How long did people mock him?","For courage to obey when we stand alone"],
["Genesis 12:1-4; 15:1-6","Abraham, who left without a map","What did God count as righteousness?","For faith to obey before we understand"],
["Genesis 18:9-15; 21:1-7","Sarah, who laughed and then laughed again","Why did she laugh the second time?","For a promise our family is still waiting on"],
["Genesis 24:58-67","Rebekah, who said I will go","What did she risk?","For our children's future marriages, chosen wisely"],
["Genesis 32:22-31","Jacob, who wrestled until dawn","What did Jacob refuse to do?","For persistence in prayer until God answers"],
["Genesis 39:1-12","Joseph, who ran from sin","What did Joseph leave behind?","For purity for every person at this table"],
["Exodus 2:1-10","Jochebed, who hid her son","What did she do when hiding was no longer possible?","For mothers protecting children in impossible situations"],
["Exodus 4:10-17","Moses, who thought he could not speak","What did God say about his mouth?","That we would stop hiding behind our weaknesses"],
["Exodus 17:8-13","Aaron and Hur, who held up the arms","What happened when the arms dropped?","For friends who hold us up when we are tired"],
["Numbers 14:6-9","Caleb, who followed fully","How old was he when he still asked for a mountain?","For a faith that does not fade with age"],
["Joshua 1:1-9","Joshua, who took over from a giant","What was he told to do with the book of the law?","For those stepping into a hard responsibility"],
["Joshua 2:1-14","Rahab, whom God rewrote","Where does her name appear later?","That God would rewrite the story of someone we know"],
["Judges 4:4-16","Deborah, a mother in Israel","What did Barak refuse to do without her?","Honouring the women God raises to lead"],
["Judges 16:15-30","Samson, strong and undisciplined","What was Samson's real weakness?","That strength in our family would come with self-control"],
["Ruth 1:16-18","Ruth, who chose a hard road","Why did she stay?","For loyalty that costs something"],
["1 Samuel 1:21-28","Hannah, who gave him back","What did Hannah do with the answered prayer?","That we would hold our children with an open hand"],
["1 Samuel 3:15-21","Samuel, who told the truth to a mentor","Why was it hard to tell Eli?","For courage to say hard true things kindly"],
["1 Samuel 20:12-17","Jonathan, who loved without envy","What did Jonathan give up for David?","Against jealousy toward those who succeed near us"],
["1 Samuel 25:14-35","Abigail, who defused a disaster","How did she prevent bloodshed?","For wisdom to calm a fight instead of feeding it"],
["2 Samuel 12:1-14","Nathan, who confronted a king","How did Nathan get through to David?","For friends who love us enough to correct us"],
["1 Kings 3:5-14","Solomon, who asked well","What did he ask for?","For wisdom over cleverness in this house"],
["1 Kings 17:8-16","The widow of Zarephath","What did she give away first?","For faith to give when we have almost nothing"],
["1 Kings 18:36-39","Elijah, who stood alone","How many prophets opposed him?","For boldness when we are outnumbered"],
["2 Kings 2:9-15","Elisha, who asked for double","What did he refuse to let go of?","That our children would want more of God than we did"],
["2 Kings 5:1-14","Naaman, who almost missed his healing","What nearly stopped him?","Against pride in our family"],
["2 Chronicles 34:1-8","Josiah, a king at eight years old","How old was he when he began to seek God?","That our children would seek God early"],
["Isaiah 6:1-8","Isaiah, who saw and said send me","What happened to his lips?","That God would find someone here willing to be sent"],
["Jeremiah 1:4-10","Jeremiah, too young, he thought","What did God say about his age?","That our young ones would not despise their own youth"],
["Daniel 1:8-20","Daniel, who purposed in his heart","When did he make his decision?","That our children would settle convictions before the test"],
["Daniel 3:16-18","Shadrach, Meshach and Abednego","What did they say about if God does not save us?","For faith that holds without guarantees"],
["Esther 4:12-17","Esther, who went anyway","What did Mordecai say to her?","That we would use our position for others"],
["Nehemiah 2:1-8","Nehemiah, who prayed and then asked","What did he do in the middle of the conversation?","For favour with those who hold authority over us"],
["Ezra 7:6-10","Ezra, who prepared his heart","What three things did he set his heart to do?","That we would study, live it, and then teach it, in that order"],
["Job 1:20-22; 2:9-10","Job, who worshipped in ruins","What did he not do?","For a grieving family we know"],
["Jonah 4:1-11","Jonah, angry about mercy","Why was Jonah upset?","Against resenting God's kindness to people we dislike"],
["Habakkuk 3:17-19","Habakkuk, who chose joy anyway","What was still missing when he rejoiced?","For joy that does not depend on our circumstances"],
["Luke 1:5-17","Zacharias and Elisabeth","How long had they waited?","For a couple we know who is waiting for a child"],
["Luke 1:26-38","Mary, who said be it unto me","What did she risk by saying yes?","For surrender to God's plan even when it costs reputation"],
["Matthew 1:18-25","Joseph, quiet and just","What was he planning before the angel came?","For husbands who protect their wives' dignity"],
["Luke 2:25-35","Simeon, who waited his whole life","What was he waiting to see?","For patience in a long wait"],
["Luke 2:36-38","Anna, who never left the temple","How did she spend her widowhood?","For the elderly in our church who pray for us"],
["Matthew 3:1-12; John 3:30","John the Baptist","What did he say must happen to him?","That we would decrease and Christ increase"],
["Luke 5:1-11","Peter, who left the boat","What did he say about himself first?","For someone here God is calling out of comfort"],
["John 1:43-51","Nathanael, honest and doubting","What was his first reaction?","That honest doubt would be welcomed at this table"],
["John 20:24-29","Thomas, who needed to see","What did Jesus offer him?","For a family member wrestling with doubt"],
["Luke 10:38-42","Martha and Mary","What did Jesus say was needful?","Against busyness crowding out sitting with Christ"],
["John 20:11-18","Mary Magdalene, first at the tomb","What made her recognise Him?","Thanking God that He calls us by name"],
["Luke 19:1-10","Zacchaeus, who climbed and then repaid","How did we know his repentance was real?","That repentance in our home would include restitution"],
["John 3:1-10","Nicodemus, who came at night","What did he not understand?","For people who are seeking quietly and afraid to ask"],
["John 4:27-42","The woman of Samaria","What did she do with her testimony?","That our home would tell others what Christ has done"],
["Acts 6:8-15; 7:54-60","Stephen, who prayed for his killers","What did he say as he died?","For persecuted believers, and for grace to forgive"],
["Acts 8:26-39","Philip, who obeyed a strange instruction","Where was he told to go?","For readiness to obey inconvenient instructions"],
["Acts 9:1-19","Saul, stopped on the road","What did Ananias have to overcome?","For someone we have written off as too far gone"],
["Acts 10:1-8,44-48","Cornelius, a praying soldier","What did God notice about him?","That our giving and praying would rise before God"],
["Acts 4:36-37; 9:26-27","Barnabas, who vouched for people","What does his name mean?","That we would be the one who encourages"],
["Acts 16:1-5; 2 Timothy 1:5","Timothy, taught by his mother and grandmother","Who taught Timothy the Scriptures?","That faith would pass down three generations in this family"],
["Acts 16:11-15","Lydia, who opened her house","What did she do after she believed?","That our home would be open for God's work"],
["Acts 18:1-4,24-28","Priscilla and Aquila, a couple serving together","What did they do for Apollos?","That we would serve God together, as one team"],
["Philemon 8-18","Onesimus, the runaway who came back","How did Paul ask Philemon to receive him?","For restored relationships in our extended family"]
];

const EVENTS = [
["Genesis 1:1-5","Creation begins","What did God speak into the darkness?","That God would speak into the dark places of our home"],
["Genesis 3:1-7","The fall","What did the serpent add to what God said?","That we would guard what our children hear and read"],
["Genesis 7:11-24","The flood","What kept Noah's family safe?","Thanking God for the safety He has provided us"],
["Genesis 11:1-9","Babel","What were the people trying to build?","Against building our name instead of God's"],
["Genesis 19:15-26","Sodom and Lot's escape","Why did Lot's wife look back?","That we would not look back at what God brought us out of"],
["Genesis 22:1-14","The ram in the thicket","What did God provide at the last moment?","For a provision we are waiting on right now"],
["Genesis 28:10-17","Jacob's ladder","What did Jacob say about that place?","That God would surprise us with His presence"],
["Genesis 37:23-36","Joseph sold into Egypt","Who was supposed to protect Joseph?","For our children when family disappoints them"],
["Exodus 3:1-6","The burning bush","Why did Moses take off his shoes?","For reverence in how we approach God"],
["Exodus 7:14-25; 12:29-32","The plagues and the last night","Why did Pharaoh keep refusing?","Against a hard heart in anyone at this table"],
["Exodus 12:1-14","The first Passover","What made the difference between houses?","Thanking God for the blood of Christ over us"],
["Exodus 14:19-31","The Red Sea opens","What did God do with the pillar of cloud?","For a way out where we can see none"],
["Exodus 16:1-8","Manna in the wilderness","Why did God give only one day at a time?","For daily bread, and daily trust"],
["Exodus 19:16-20; 20:18-21","Sinai shakes","How did the people feel?","That we would hold God's holiness seriously"],
["Exodus 32:15-24","The golden calf","What excuse did Aaron give?","Against blaming others for our own choices"],
["Numbers 13:26-14:10","Twelve spies report back","What did the ten focus on?","That we would report faith and not fear to our children"],
["Numbers 21:4-9","The bronze serpent","What did the people have to do to live?","Thanking God that looking to Christ is enough"],
["Joshua 3:9-17","Crossing the Jordan","When did the water stop?","For courage to step before we see the way clear"],
["Joshua 6:1-5,15-21","Jericho falls","How many days did they walk in silence?","For patience in an obedience that looks pointless"],
["Judges 7:15-22","Gideon's three hundred","What did they carry instead of weapons?","That God's power would be obvious in our weakness"],
["1 Samuel 4:1-11","The ark captured","Why did Israel lose?","Against treating holy things as good luck charms"],
["1 Samuel 17:38-51","David and Goliath","What did David say the battle belonged to?","For the giant standing in front of our family"],
["2 Samuel 6:1-15","The ark comes to Jerusalem","Why did David dance?","For unashamed worship in this home"],
["1 Kings 8:22-30,54-61","Solomon dedicates the temple","What did Solomon ask God to do with prayers?","Dedicating this house to God afresh tonight"],
["1 Kings 18:20-40","Fire falls on Carmel","What did Elijah ask the people to decide?","That we would stop limping between two opinions"],
["2 Kings 4:8-17","A room built for a prophet","What did the woman build?","That we would make room for God's servants"],
["2 Kings 6:8-17","The mountain full of horses","What did the servant see after prayer?","That God would open our eyes to His help"],
["2 Kings 19:14-19,35-37","Hezekiah spreads the letter","What did Hezekiah do with the threatening letter?","For a threat our family is facing, laid before God"],
["2 Chronicles 20:14-25","Singers sent ahead of the army","Who went first into the battle?","For praise before the answer arrives"],
["2 Chronicles 34:14-21","The lost book is found","What happened when the king heard it read?","That God's word would still shake us"],
["2 Kings 25:1-12","Jerusalem falls","Why did it happen?","That we would take warnings seriously"],
["Daniel 3:19-27","The fiery furnace","Who was the fourth man?","That Christ would be with us in the fire, not only after it"],
["Daniel 5:1-6,25-30","Writing on the wall","What was the king doing when it appeared?","Against carelessness with holy things"],
["Daniel 6:16-24","The lions' den","What did the king say at the stone?","For deliverance for a believer in danger somewhere tonight"],
["Ezra 3:8-13","The foundation is laid","Why were some weeping and some shouting?","For a family rebuilding after loss"],
["Nehemiah 6:1-9,15-16","The wall finished in fifty-two days","How did Nehemiah answer the distractions?","Against distractions pulling us off God's work"],
["Nehemiah 8:1-12","The people hear the law and weep","What did the leaders tell them to do?","That the joy of the Lord would be our strength"],
["Esther 5:1-8; 7:1-6","Esther's banquet","Why did she wait for the second banquet?","For wisdom about timing"],
["Jonah 3:1-10","Nineveh repents","Who repented first, the king or the people?","For revival in Buea, beginning in our house"],
["Luke 1:26-38","The announcement to Mary","What did the angel say was impossible with God?","For an impossible thing in our family"],
["Luke 2:1-20","The night He was born","Who were told first?","That God chooses the overlooked"],
["Matthew 2:1-12","The wise men arrive","What three gifts did they bring?","That we would bring Christ our best, not our leftovers"],
["Matthew 3:13-17","The baptism of Jesus","What did the Father say?","That our children would hear their Father's approval"],
["Matthew 4:1-11","Forty days of temptation","How did Jesus answer every time?","That Scripture would be our weapon, not our argument"],
["John 2:1-11","Water into wine at Cana","Who knew where the wine came from?","That God would honour our marriage as He honoured that wedding"],
["Matthew 5:1-12","The sermon on the mountain","Which blessing surprises you most?","That our family would want what God calls blessed"],
["Mark 4:35-41","The storm stilled","What did Jesus ask about their faith?","For peace in the storm we are in"],
["John 6:1-14","Five loaves and two fish","Whose lunch was it?","That our children would offer God what little they have"],
["Matthew 14:22-33","Walking on the water","What did Peter hear before he stepped out?","For obedience that steps out on a word"],
["Matthew 17:1-8","The transfiguration","What did the voice say to do?","That we would hear Christ above every other voice"],
["Luke 15:11-32","The son comes home","What was the older brother's problem?","Against a resentful heart in the one who stayed"],
["John 11:38-44","Lazarus raised","What did Jesus tell the others to do?","That we would help remove what binds people"],
["Matthew 21:1-11","The triumphal entry","What did the crowd shout?","That our praise would not depend on the crowd"],
["Luke 22:14-20","The last supper","What did He say to do in remembrance?","Preparing our hearts for the Lord's supper"],
["Matthew 26:36-46","Gethsemane","What did Jesus pray three times?","For surrender when God's will is hard"],
["Luke 22:54-62","Peter denies Him","What made Peter weep?","For mercy after our own failures"],
["Luke 23:32-46","The cross","What did the thief ask for?","Worshipping Christ for the exchange He made"],
["Matthew 28:1-10","The resurrection","What was the first word of the angel?","That fear would give way to joy in this house"],
["Luke 24:13-35","The road to Emmaus","When did they recognise Him?","That Christ would open the Scriptures to us tonight"],
["Acts 1:6-11","The ascension","What were they told to stop doing?","For readiness for His return"],
["Acts 2:1-13","Pentecost","What did people think at first?","For the power of the Holy Ghost in our home"],
["Acts 3:1-10","The lame man at the gate","What did Peter say he did not have?","That we would give what we have, not mourn what we lack"],
["Acts 12:5-17","Peter freed from prison","What was the church doing?","For the power of a praying church"],
["Acts 16:22-34","The earthquake at midnight","What did the jailer ask?","That our conduct under pressure would lead someone to Christ"],
["Acts 27:13-25,39-44","The shipwreck","What did Paul say in the middle of the storm?","For safety for everyone travelling from this house"],
["Revelation 4:1-11","The throne room","What do they never stop saying?","That worship would fill our home the way it fills heaven"],
["Revelation 21:1-7","All things made new","What will no longer exist?","That our whole family would be there, with nobody missing"]
];
