/* ============================================================
   WHAT THE EVANS FAMILY ACTUALLY DID
   Pulled from Raising Kingdom Kids, chapter by chapter. These are
   practices, not principles. Each one carries the age it starts,
   because most of what he describes was aimed at older children,
   and yours are 5, 4 and 1.
     start: 'now'   works with your three today
     start: <age>   wait until your eldest reaches this age
   ============================================================ */

const PRACTICES = [
{g:'The table', id:'t1', start:'now', t:'Eat the evening meal together, every night',
 e:'Evans says that during the busiest season of his ministry, with Promise Keepers exploding and the church growing fast, they missed few if any family meals when he was in town. When he travelled, Lois carried the routine on without him.',
 y:'This is the single most transferable thing in the book, and a 1 year old can be at the table. Fix the hour and hold it. Missing it should feel like missing work.'},
{g:'The table', id:'t2', start:'now', t:'Read a portion and let each person say what it means',
 e:'Jonathan Evans remembers sitting down every evening, each of them reading a Scripture and talking about its meaning. He calls the dinner table the place where he and his siblings discovered the kingdom of God.',
 y:'At 5 and 4 they cannot read yet, so you read and they answer. Ask what happened in the story, not what it means. Six to eight verses, no more.'},
{g:'The table', id:'t3', start:'now', t:'Pray together at the table, out loud, by name',
 e:'Priscilla writes that they were prayed for by their parents at the kitchen table. Evans is direct that praying with your children daily beats praying only for them.',
 y:'A 4 year old can pray one sentence. A 5 year old can pray for one named person. Let the 1 year old hear his own name said to God.'},
{g:'The table', id:'t4', start:'now', t:'Use Scripture memory cards at the table',
 e:'Lois bought memory cards and both she and Tony led the children in reading, discussing and memorising them at dinner. She names this as one of the deliberate ways they obeyed Deuteronomy 6.',
 y:'Use the little-ones verses in this app. Five to eight words is the right length at 4 and 5. Write each on a card and stand it on the table for a fortnight.'},
{g:'The table', id:'t5', start:'now', t:'Make the table fun on purpose',
 e:'He wanted table time enjoyable above all. He would say, let us go round and everyone tell their best joke or do an impersonation. Chrystal remembers being doubled over an empty plate laughing at a corny joke.',
 y:'At these ages this is most of the win. A child who enjoys the altar keeps it at twenty. Silly voices for the Bible characters are not irreverence, they are attendance.'},
{g:'The table', id:'t6', start:6, t:'Teach table manners deliberately',
 e:'The boys were taught how to seat a lady at the table. The girls were taught how to be seated by a gentleman. Etiquette was taught at the table, not assumed.',
 y:'Start the simple version now, please and thank you and waiting to be served. The seating lesson lands around six or seven.'},
{g:'The table', id:'t7', start:'now', t:'Bring guests to your table on purpose',
 e:'They deliberately hosted visiting missionaries and ministry workers, not only for hospitality but to reinforce their value system. The children heard the stories and were required to pitch in with the serving.',
 y:'Your Deeper Life house fellowship leader, a visiting minister, an older couple from the assembly. Your 5 year old can carry the water. That is the lesson.'},
{g:'The table', id:'t8', start:'now', t:'Check chores and homework at the table',
 e:'He used the table to check whether the children were keeping their responsibilities and getting homework done well and turned in on time.',
 y:'At 5 and 4 this is two or three small jobs. Did you put your shoes away. Did you help mama. Check it at the same place every day.'},

{g:'The house itself', id:'h1', start:'now', t:'Hang Scripture on the walls',
 e:'Lois bought them and Tony hung them. Signs reading As for me and my house we will serve the Lord, By grace are you saved, and I am the vine you are the branches, still hang in their home today.',
 y:'Cheap and permanent. A child who cannot yet read learns the shape of the words before the meaning. Do a few this month.'},
{g:'The house itself', id:'h2', start:'now', t:'Hang words about the home and family too',
 e:'She also bought decor reading The Gathering Place and Family Matters, and a framed print in the kitchen reading Write it on your heart that the ones you love are life\u2019s most precious gifts.',
 y:'This one is for your wife as much as the children. It says out loud, in the room, that this house is worth something.'},
{g:'The house itself', id:'h3', start:'now', t:'A sign for each child with their name, its meaning and a verse',
 e:'A vertical set of signs beside the doorway to the bedrooms, one per child. Anthony, priceless one, with his verse. Jonathan, God\u2019s gracious gift, with Psalm 84:11. Each child had a name, a meaning and a word from God attached to it.',
 y:'Build these in the Name cards section below and print them. Do all three, including the baby. Read each child their own sign until they know it by heart.'},
{g:'The house itself', id:'h4', start:'now', t:'Praise music playing on ordinary days',
 e:'Priscilla writes that praise music wafted through the air every day, not just on Sunday, and that the Word became alive to her as a child because it was around her everywhere.',
 y:'Free. Put it on while your wife cooks and while the children play. This is the cheapest item on the whole list.'},
{g:'The house itself', id:'h5', start:'now', t:'Tell Bible stories with something they can see',
 e:'Before electronic options, Priscilla remembers the flannelboard, the soft black board with cut-out figures her parents used to put the stories in front of them.',
 y:'Exactly right for 5, 4 and 1. A picture Bible, paper cut-outs, drawings on the back of an exercise book. They must see it, not only hear it.'},
{g:'The house itself', id:'h6', start:'now', t:'Cap the television, and cap it for yourselves too',
 e:'Thirty minutes a night on school nights. Chrystal notes that this meant thirty minutes for the parents as well while the children were awake. He admits he broke his own rule at times, and says purposeful is the aim, not perfect.',
 y:'For you this is the phone, not the television. Thirty minutes of screen while they are awake. They are watching where your eyes go.'},

{g:'Being there', id:'a1', start:'now', t:'Own the school run',
 e:'Driving the children to school was always his duty. He volunteered for it. He says he wanted to show his children honour in that way.',
 y:'Your 5 year old is starting school. Take that job and do not give it back. Fifteen minutes each way is the best talking time you will get all day.'},
{g:'Being there', id:'a2', start:'now', t:'Sit with them at homework time, every day',
 e:'Homework time at the end of each day was his. He sat with Jonathan, who struggled badly, often until midnight, at the height of his travelling and preaching. He refused to just fill in the answers, because that would not have prepared his son.',
 y:'At 5 this is ten minutes of letters and numbers. The habit is what you are building now, not the content.'},
{g:'Being there', id:'a3', start:'now', t:'Always take their call',
 e:'Whenever his children called, whether he was in a meeting or not, he took the call. He writes that accessibility communicates commitment and value more clearly than almost anything else you can do.',
 y:'Yours are too small to phone yet, so the version for now is this: when a child comes to you while you are on the phone, you put the phone down.'},
{g:'Being there', id:'a4', start:'now', t:'Limit travel to what the family agrees to',
 e:'He limited his travelling to what was agreeable to his family, and would fly back from a speaking engagement to attend a school event and then return.',
 y:'Ask your wife which trips and late nights actually cost her, and cut one this month. Let her be the one who decides which.'},
{g:'Being there', id:'a5', start:'now', t:'Be so ordinary at home that they do not notice you are important',
 e:'Priscilla told a friend that growing up she never really knew her father was a prominent national preacher, because he always seemed to be around.',
 y:'This is the whole point of the section. Aim for your children finding you unremarkable at home. That is the compliment.'},
{g:'Being there', id:'a6', start:'now', t:'Hold set times for family meetings and direction',
 e:'He tells parents to go ahead and set times for family meetings, guidance and direction, following Deuteronomy 6: when you sit, when you walk, when you lie down, when you rise up.',
 y:'One short family meeting a week, ten minutes, Sunday afternoon. What went well, what we are fixing, what is coming.'},

{g:'The blessing', id:'b1', start:'now', t:'Speak favour and future over each child by name',
 e:'He writes that most prisoners he has met never received the blessing, never heard a parent speak over them words of favour and future. The blessing is based on who the child is, not what they achieved.',
 y:'Say it at bedtime, out loud, using their name. God has a good future for you. You are His. Do it for the 1 year old too. He is learning your voice before your words.'},
{g:'The blessing', id:'b2', start:'now', t:'Dedicate them, then dedicate again when they understand',
 e:'He suggests a dedication ceremony as a baby and a second one at an age of understanding. It need not be formal. Invite others to pray over the child, and present them with a Bible to mark the passing of the blessing.',
 y:'Your church already does infant dedication. Put the second one in the diary for your eldest at around ten, and buy the Bible in advance.'},
{g:'The blessing', id:'b3', start:'now', t:'Split your attention evenly between them',
 e:'He calls it one of his greatest failures as a father. Because Jonathan struggled in school, the time he gave him was disproportionate, and Anthony went short. He names Joseph\u2019s coat as the warning.',
 y:'With a 1 year old in the house this is the live risk right now. The baby eats the hours. Your 4 year old will read that as being replaced unless you deliberately spend time alone with him.'},
{g:'The blessing', id:'b4', start:'now', t:'Go back and repair a blessing you failed to give',
 e:'Rather than concluding it was too late with Anthony, he made a conscious choice to reverse it. Now barely two or three days pass without them speaking, and they end up at the same events.',
 y:'Applies to your wife first. You have months to make up. He is proof it can be done late.'},
{g:'The blessing', id:'b5', start:'now', t:'Take them with you when you go',
 e:'He liked to include the children whenever he could, and describes taking Anthony with him to preach in Baltimore, where they also saw his grandparents.',
 y:'Take the 5 year old to house fellowship. Take one child on an errand alone. Alone is the operative word.'},

{g:'Money', id:'m1', start:'now', t:'Teach three words in order: give, save, spend',
 e:'Give first, honouring God with the firstfruits. Save second, never spending everything. Spend third. He is explicit that spending is not wrong, it is just third.',
 y:'Your 5 year old can grasp this with coins. Three tins, in that order, left to right. Say the three words every time.'},
{g:'Money', id:'m2', start:'now', t:'Keep a shoebox in the kitchen for the tenth',
 e:'They had a shoebox in the kitchen where the children put ten percent of their allowance every week, which was then given as an offering or to missions.',
 y:'Start it this week. The tracker in this app counts it. Let your 5 year old carry the box to church himself.'},
{g:'Money', id:'m3', start:14, t:'Let them work as soon as they legally can',
 e:'They encouraged all four children to get jobs as soon as they were legally old enough. He notes they were far less willing to spend money they had earned themselves than money that came from him.',
 y:'Years away. Note it and move on.'},

{g:'Their gifts', id:'g1', start:'now', t:'Study each child\u2019s bent and follow it, not yours',
 e:'He admits he pushed football at Anthony because of his own unfulfilled dream, and calls it loving himself rather than loving his son. Proverbs 22:6, in the way he should go, means according to the child\u2019s own wiring.',
 y:'At 5 and 4 you are only observing. What do they do when nobody organises them. Write it down and stop steering.'},
{g:'Their gifts', id:'g2', start:'now', t:'Go to absurd lengths to let them test an interest',
 e:'When Anthony wanted to be a vet and asked to buy a donkey, they visited animal farms, and Evans knocked on the neighbours\u2019 doors to ask whether they would mind a donkey in the yard. They never got the donkey.',
 y:'This is the standard. Not that you buy it, that you take it seriously enough to go and find out.'},

{g:'Discipline', id:'d1', start:'now', t:'Set the boundary before, never after',
 e:'He is firm that disciplining a child for something they did not know was wrong produces confusion and animosity, not growth. God always sets clear boundaries with us first.',
 y:'At 4 and 5 the rule must be said in advance, in short words, and repeated. If you did not say it before, this one is on you, not the child.'},
{g:'Discipline', id:'d2', start:'now', t:'Follow through every time you have warned',
 e:'He respected his own father because the man always followed through on his warnings. A rule that is sometimes enforced teaches a child to gamble.',
 y:'Only give warnings you will actually carry out while tired at 8pm. Fewer rules, kept absolutely.'},
{g:'Discipline', id:'d3', start:'now', t:'Never correct while you are angry',
 e:'Discipline must flow out of compassion for the child\u2019s wellbeing and future, not out of your own irritation.',
 y:'With three under six you will be provoked daily. Walk out of the room first. Correct after, not during.'},
{g:'Discipline', id:'d4', start:'now', t:'Know that what works on one will not work on another',
 e:'Of their four children, one was disciplined far more than the others and one hardly at all. For some children being sent to their room is a punishment, for another it is a reward. He had to discover the way to reach each child.',
 y:'Your 5 and your 4 will already be different. Do not run one system across both and call it fairness.'},
{g:'Discipline', id:'d5', start:'now', t:'Always close it with a hug and I love you',
 e:'He would often follow up grounding, spanking or lecturing with a hug and telling that child he loved them, because he wanted the child to both hear and see the heart the correction came from.',
 y:'Non negotiable at these ages. The correction is not finished until the child is back in your arms. Never let one go to bed unreconciled.'},
{g:'Discipline', id:'d6', start:7, t:'Make boundaries a door to more freedom',
 e:'Keep the ten o\u2019clock curfew faithfully and in time it becomes half past ten. He teaches that rewards come from honouring boundaries, and that it is fine to reward obedience because God does.',
 y:'Later, but the seed works now in small currency. Tidy without being asked all week and you choose Saturday\u2019s outing.'},
{g:'Discipline', id:'d7', start:5, t:'Misbehaviour at school has consequences at home',
 e:'His parents were adamant that any disciplinary problem in class was to be caused by other people\u2019s children. A teacher was to be respected and obeyed, and the family honour was at stake.',
 y:'Your eldest is starting school. Say this to him now, before the first incident, and then hold it.'},
{g:'Discipline', id:'d8', start:'now', t:'Admit your own mistakes to them, out loud',
 e:'He calls it one of the greatest things a parent can do, because the child then sees modelled how to respond to their own mistakes. Anthony remembers his father opening the door and saying, I apologise for the way I hurt you. No excuses, no disclaimers.',
 y:'Your 4 year old will remember the day you said sorry to him far longer than the day you were right.'},

{g:'Their friends', id:'f1', start:8, t:'Bring the friends into the house',
 e:'Rather than only forbidding friendships, he asked his daughters to bring their friends home so the family could spend time with them, and discussed the influence afterwards.',
 y:'Starts once school friendships form. Note it for your eldest in two or three years.'},
{g:'Their friends', id:'f2', start:8, t:'Sometimes just say no more',
 e:'He admits he struggled with the balance, and that sometimes he simply said no more about a particular friend.',
 y:'Later. But the fact that he found it hard and still did it is the useful part.'},
{g:'Their friends', id:'f3', start:6, t:'The eagle and the turkeys',
 e:'His father repeatedly told Anthony the story of an eagle raised among turkeys who never reached his potential, then said: Anthony, you are an eagle. Do not surround yourself with turkeys.',
 y:'One story, told many times over years, that a grown man still quotes. Find your own version and start telling it at six.'},

{g:'Purity', id:'p1', start:16, t:'One lunch, one to one, about purity',
 e:'At seventeen he took Jonathan out to lunch alone for a serious conversation about God\u2019s expectation of sanctification before he left for university. He gave him a key necklace, explaining the key was made for one specific lock and was to be given only to the woman he would marry.',
 y:'Twelve years away for your eldest. Put it in the calendar anyway. Things you schedule a decade early are the ones that happen.'},

{g:'Service', id:'s1', start:'now', t:'Adopt a family at Christmas and let the children do the work',
 e:'Chrystal describes the family tradition: photographs of the children being helped taped to her own children\u2019s bedroom door, praying for them by name, choosing gifts, resisting the urge to keep the best ones, and then going with their parents to deliver them in person.',
 y:'Your 5 and 4 year old can absolutely do this in Buea this December. The going in person is the part that forms them.'},
{g:'Service', id:'s2', start:'now', t:'Serve in small ordinary ways where they can see',
 e:'He gives giving the postman a bottle of water as an example, and insists service is a mindset and a way of life rather than an event.',
 y:'Send the 4 year old with something to the neighbour. Let him hand it over himself.'},

{g:'Keeping it going', id:'k1', start:'now', t:'A monthly gathering where verses are recited',
 e:'Now that his children have their own children, they hold a family lunch every month where the grandchildren climb on a chair and recite the passages they have memorised over the previous month.',
 y:'Start this now with three small children and it will be thirty years old by the time yours have theirs. Pick a Sunday each month.'},
{g:'Keeping it going', id:'k2', start:'now', t:'Push through the commotion instead of quitting',
 e:'He admits his four children talked out of turn, pouted and made it commotion rather than devotion, and that he sometimes called it off and sent everyone to their rooms. But more often than not he stuck it out, and was later surprised by a child repeating something he was sure nobody had heard.',
 y:'This is the one you will need most. With a 1, 4 and 5 year old, most evenings will look like failure. Keep going. They are absorbing more than they show.'},
{g:'Keeping it going', id:'k3', start:'now', t:'When one parent cannot, the other carries it',
 e:'When he was travelling, Lois continued the discipleship routine in the home without him.',
 y:'This is the argument for the roster. It should not collapse because you are away or tired. Two people, one altar.'}
];

/* ---- Memory verses sized for a 4 and a 5 year old. One a fortnight. ---- */
const LITTLEVERSES = [
["God is love.","1 John 4:8"],["Jesus wept.","John 11:35"],["Love one another.","John 13:34"],
["Children, obey your parents.","Ephesians 6:1"],["Be ye kind one to another.","Ephesians 4:32"],
["The Lord is my shepherd.","Psalm 23:1"],["I will trust in thee.","Psalm 56:3"],
["God is my helper.","Psalm 54:4"],["The Lord is good.","Psalm 100:5"],
["Pray without ceasing.","1 Thessalonians 5:17"],["Rejoice evermore.","1 Thessalonians 5:16"],
["In everything give thanks.","1 Thessalonians 5:18"],["God is faithful.","1 Corinthians 10:13"],
["Speak every man truth.","Ephesians 4:25"],["Honour thy father and thy mother.","Exodus 20:12"],
["Be strong and of a good courage.","Joshua 1:9"],["A soft answer turneth away wrath.","Proverbs 15:1"],
["Thy word is a lamp unto my feet.","Psalm 119:105"],["Fear not, for I am with thee.","Isaiah 41:10"],
["Trust in the Lord with all thine heart.","Proverbs 3:5"],
["Christ Jesus came to save sinners.","1 Timothy 1:15"],["Suffer the little children to come unto me.","Mark 10:14"],
["As for me and my house, we will serve the Lord.","Joshua 24:15"],
["I can do all things through Christ.","Philippians 4:13"]
];

/* ---- A track built for children under six. Short, concrete, one picture each. ---- */
const LITTLE = [
["Genesis 1:1-5","God makes light","What did God make first?","Thank God for the sun that wakes us"],
["Genesis 1:20-25","God makes the animals","Which animal is your favourite?","Thank God for the animals He made"],
["Genesis 1:26-28","God makes people","Who did God make last?","Thank God for making you"],
["Genesis 2:1-3","God rests","What did God do on the seventh day?","Thank God for rest and for sleep"],
["Genesis 3:1-6","The first wrong thing","Who told the lie?","Ask God to help us obey"],
["Genesis 6:13-22","Noah builds a big boat","How did Noah know what to build?","Thank God that He tells us what to do"],
["Genesis 7:1-10","The animals go in two by two","Who shut the door?","Thank God that He keeps us safe"],
["Genesis 9:8-17","The rainbow","What does the rainbow mean?","Thank God that He keeps His promises"],
["Genesis 12:1-5","Abraham goes on a journey","Did Abraham know where he was going?","Ask God for courage to obey"],
["Genesis 21:1-7","Sarah has a baby","Why did Sarah laugh?","Thank God that nothing is too hard for Him"],
["Genesis 24:12-20","A kind girl at the well","What did Rebekah do for the camels?","Ask God to make us helpful"],
["Genesis 37:3-11","Joseph\u2019s special coat","Why were the brothers cross?","Ask God to take away jealousy"],
["Genesis 41:14-16","Joseph helps the king","Who did Joseph say gave him the answer?","Thank God for giving wisdom"],
["Genesis 45:1-7","Joseph forgives","What did Joseph do when he saw his brothers?","Ask God to help us forgive quickly"],
["Exodus 2:1-10","A baby in a basket","Who found the baby?","Thank God for mothers who protect us"],
["Exodus 3:1-6","A bush on fire","Why did Moses take off his shoes?","Thank God that He is holy"],
["Exodus 14:21-25","A dry road in the sea","How did the people cross?","Thank God that He makes a way"],
["Exodus 16:13-16","Bread from the sky","How much could they pick each day?","Thank God for our food today"],
["Exodus 20:12","Honour your father and mother","What does honour mean?","Ask God to help us obey at once"],
["Joshua 6:15-20","The walls fall down","How many times did they walk round?","Ask God to help us keep going"],
["Judges 6:11-16","God calls a shy man","What did God call Gideon?","Thank God that He sees who we can be"],
["Ruth 1:14-17","Ruth stays","Who did Ruth choose to stay with?","Thank God for people who stay"],
["1 Samuel 1:24-28","Hannah gives Samuel to God","What did Hannah do with her boy?","Give our family back to God"],
["1 Samuel 3:1-10","Samuel hears a voice","What did Samuel say to God?","Ask God to help us listen"],
["1 Samuel 16:6-13","God picks the youngest","What does God look at?","Thank God that He sees our hearts"],
["1 Samuel 17:41-50","The boy and the giant","What did David take with him?","Ask God for courage when things are big"],
["1 Kings 17:2-6","Birds bring food","Who fed Elijah?","Thank God that He feeds us"],
["1 Kings 18:36-39","Fire from heaven","What did the people say after?","Say together, the Lord is God"],
["2 Kings 4:1-7","The oil that kept coming","What did the woman have at the start?","Thank God that He makes little into much"],
["2 Kings 5:9-14","Wash seven times","Why was Naaman cross?","Ask God to help us obey small things"],
["Nehemiah 2:17-18","Let us build","What did they say together?","Ask God to help our family work together"],
["Esther 4:13-16","A brave queen","What did Esther decide to do?","Ask God for bravery"],
["Psalm 23:1-3","The Lord is my shepherd","What does a shepherd do?","Thank God for looking after us"],
["Psalm 100","Make a joyful noise","How should we come to God?","Sing one song together"],
["Psalm 139:13-16","God made you","Who made your fingers?","Thank God for each child by name"],
["Daniel 1:8-15","Daniel says no thank you","What did Daniel decide?","Ask God to help us choose right"],
["Daniel 3:19-27","Three boys in the fire","How many men did the king see?","Thank God that He is with us"],
["Daniel 6:16-23","Daniel in with the lions","What did Daniel keep doing?","Ask God to help us pray every day"],
["Jonah 1:11-17","Jonah runs away","Where did Jonah end up?","Ask God to help us obey the first time"],
["Jonah 2:1-2,10","Jonah prays inside the fish","Where can we pray?","Thank God that He hears us anywhere"],
["Luke 1:26-33","An angel visits Mary","What was the baby to be called?","Thank God for sending Jesus"],
["Luke 2:1-7","Jesus is born","Where did they lay Him?","Thank God that Jesus came for us"],
["Luke 2:8-16","The shepherds run to see","Who was told first?","Thank God that He tells ordinary people"],
["Matthew 2:9-11","The wise men bring gifts","What did they do when they saw Him?","Give God something today"],
["Matthew 3:13-17","Jesus is baptised","What did the voice say?","Thank God that He is pleased with Jesus"],
["Mark 4:35-39","Jesus stops the storm","What did Jesus say to the wind?","Ask God for peace when we are afraid"],
["John 6:5-13","A boy shares his lunch","What did the boy have?","Ask God to help us share"],
["Mark 10:13-16","Jesus and the children","What did Jesus do with them?","Thank God that Jesus wants children"],
["Luke 19:1-6","A small man in a tree","Why did Zacchaeus climb?","Thank God that Jesus calls us by name"],
["John 11:38-44","Lazarus comes out","What did Jesus say?","Thank God that Jesus is stronger than death"],
["Luke 15:3-6","The lost sheep","How many did he leave to find one?","Thank God that He comes to find us"],
["Luke 15:20-24","The boy comes home","What did the father do when he saw him?","Thank God that He runs to meet us"],
["Luke 10:30-35","The kind stranger","Who stopped to help?","Ask God to help us stop and help"],
["Matthew 6:9-13","How to pray","What do we call God when we pray?","Say the Lord\u2019s prayer together"],
["Luke 22:19-20","The last supper","What did Jesus tell them to remember?","Thank God for the Lord\u2019s supper"],
["Luke 23:33-34","Jesus on the cross","What did Jesus pray for the soldiers?","Thank Jesus for taking our punishment"],
["Matthew 28:1-8","The empty tomb","What did the angel say?","Say together, He is risen"],
["Acts 1:9-11","Jesus goes up","Where did Jesus go?","Thank God that Jesus is coming back"],
["Acts 2:1-4","The Holy Spirit comes","What did it sound like?","Ask God for the Holy Spirit in our home"],
["Acts 16:25-31","Singing in prison","What were they doing at midnight?","Sing one song, even on a hard day"]
];
